// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Read from environment variables with fallback to production
const SUPABASE_URL =
  import.meta.env.VITE_SUPABASE_URL ||
  'https://penzhrrqhmjgwcqnugeq.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlbnpocnJxaG1qZ3djcW51Z2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwODY5MDcsImV4cCI6MjA2MTY2MjkwN30.fhhCcqBmYXUbxiX62gZX5GAwrXIeQ-8jDcU76SrdpJU';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
  },
);
